// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxxhywdhvawynznknpdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4eGh5d2RodmF3eW56bmtucGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1ODM4MTQsImV4cCI6MjA0OTE1OTgxNH0.Df-Ou62C6xOn5s9iHLhOPXPMEbKZVZrNv11XT6Z2iuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);